3rd Semester Project/WebApp/Controllers/SharedController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class SharedController : Controller
    {
        public ActionResult ShoppingCartOverview()
        {
            return View();
        }

        public ActionResult PaymentGateway()
        {
            return View();
        }

        public void SetViewBagTotal(string Total)
        {
            ViewBag.Total = Total;
        }
    }
}

3rd Semester Project/WebApp/Views/Shared/PaymentGateway.cshtml
@using Microsoft.AspNet.Identity;


<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>

<div class="container">
    <div class='row'>
        <div class='col-md-4'></div>
        <div class='col-md-4'>
            <form accept-charset="UTF-8" class="require-validation" id="payment-form">
                <div class='form-row'>
                    <div class='col-xs-12 form-group required'>
                        <label class='control-label'>Name on Card</label>
                        <input class='form-control name-input' size='4' type='text' required>
                    </div>
                </div>
                <div class='form-row'>
                    <div class='col-xs-12 form-group card required'>
                        <label class='control-label'>Card Number</label>
                        <input autocomplete='off' class='form-control card-number number-only' size='20' type='text' minlength="12" maxlength="19" required pattern="^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})$">
                    </div>
                </div>
                <div class='form-row'>
                    <div class='col-xs-4 form-group cvc required'>
                        <label class='control-label'>CVC</label>
                        <input autocomplete='off' class='form-control card-cvc number-only' placeholder='ex. 311' size='4' type='text' minlength="3" maxlength="3" required pattern="[0-9]{3}">
                    </div>
                    <div class='col-xs-4 form-group expiration required'>
                        <label class='control-label'>Expiration</label>
                        <input class='form-control card-expiry-month number-only' placeholder='MM' size='2' type='text' minlength="2" maxlength="2" required pattern="0[1-9]|1[0-2]">
                    </div>
                    <div class='col-xs-4 form-group expiration required'>
                        <label class='control-label'> </label>
                        <input class='form-control card-expiry-year number-only' placeholder='YYYY' size='4' type='text' minlength="4" maxlength="4" required pattern="\b20(2[1-9]|2[0-5])\b">
                    </div>
                </div>
                <div class='form-row'>
                    <div class='col-md-12'>
                        <div class='form-control total btn btn-info'>
                            Total:
                            <span id="price" class='amount'> </span>
                        </div>
                    </div>
                </div>
                <div class='form-row'>
                    <div class='col-md-12 form-group'>
                        <button class='form-control btn btn-primary submit-button' type='submit'>Pay »</button>
                    </div>
                </div>
                <div class='form-row'>
                    <div class='col-md-12 error form-group hide'>
                        <div class='alert-danger alert'>
                            Please correct the errors and try again.
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class='col-md-4'></div>
    </div>
</div>

<style>
    .submit-button {
        margin-top: 10px;
    }

    .col-md-4 {
        padding-top: 25px;
    }
</style>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

<script>

            $(document).ready(function () {
                var price = localStorage.getItem('price');
                $('#price').text(price);
                localStorage.clear();
            });

            $(document).ready(function () {
                $(".number-only").inputFilter(function (value) {
                    return /^\d*$/.test(value);
                });
            });

        $(function() {
            $('form.require-validation').bind('submit', function (e) {
                event.preventDefault();
                var $form = $(e.target).closest('form'),
                    inputSelector = ['input[type=email]', 'input[type=password]',
                        'input[type=text]', 'input[type=file]',
                        'textarea'].join(', '),
                    $inputs = $form.find('.required').find(inputSelector),
                    $errorMessage = $form.find('div.error');

                $errorMessage.addClass('hide');
                $('.has-error').removeClass('has-error');
                $inputs.each(function (i, el) {
                    var $input = $(el);
                    if ($input.val() === '') {
                        $input.parent().addClass('has-error');
                        $errorMessage.removeClass('hide');
                    }
                });
                
                
                buy();
            });
        });

    function buy() {
                $.ajax({
                type: "GET",
                url: "/UserTickets/CompleteTransaction?userId=@User.Identity.GetUserId()",
                success: function () {
                    location.href = "/Home/Index";
                },
                failure: function () {
                    alert("The system failed in processing your transaction!");
                },
                error: function () {
                    alert("There was an error in processing your transaction!");
                }
            });

    };

    // Restricts input for the set of matched elements to the given inputFilter function.
    (function ($) {
        $.fn.inputFilter = function (inputFilter) {
            return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function () {
                if (inputFilter(this.value)) {
                    this.oldValue = this.value;
                    this.oldSelectionStart = this.selectionStart;
                    this.oldSelectionEnd = this.selectionEnd;
                } else if (this.hasOwnProperty("oldValue")) {
                    this.value = this.oldValue;
                    this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
                } else {
                    this.value = "";
                }
            });
        };
    }(jQuery));


    $(function () {

        $('.name-input').keydown(function (e) {

            if (e.ctrlKey || e.altKey) {

                e.preventDefault();

            } else {

                var key = e.keyCode;

                if (!((key == 8) || (key == 32) || (key == 46) || (key >= 35 && key <= 40) || (key >= 65 && key <= 90))) {

                    e.preventDefault();

                }

            }

        });

    });

        //$(function () {
        //    var $form = $("#payment-form");

        //    $form.on('submit', function (e) {
        //        if (!$form.data('cc-on-file')) {
        //            e.preventDefault();
        //            Stripe.setPublishableKey($form.data('stripe-publishable-key'));
        //            Stripe.createToken({
        //                number: $('.card-number').val(),
        //                cvc: $('.card-cvc').val(),
        //                exp_month: $('.card-expiry-month').val(),
        //                exp_year: $('.card-expiry-year').val()
        //            }, stripeResponseHandler);
        //        }
        //    });

        //    function stripeResponseHandler(status, response) {
        //        if (response.error) {
        //            $('.error')
        //                .removeClass('hide')
        //                .find('.alert')
        //                .text(response.error.message);
        //        } else {
        //            // token contains id, last4, and card type
        //            var token = response['id'];
        //            // insert the token into the form so it gets submitted to the server
        //            $form.find('input[type=text]').empty();
        //            $form.append("<input type = 'hidden' name = 'reservation[stripe_token]' value = '" + token + "' /> ");
        //            $form.get(0).submit();
        //        }
        //    }
        //})

</script>

}

3rd Semester Project/WebApp/Views/Shared/ShoppingCart.cshtml
@using Microsoft.AspNet.Identity
@using WebApp.Controllers;
@model IEnumerable<WebApp.Models.DisplayShopingCartTicket>

@*Will be helpful: https://stackoverflow.com/questions/27517912/persisting-information-between-two-view-requests-in-mvc*@

<head>
    <style>
        .btn1 {
            border: 2px solid black;
            background-color: black;
            color: white;
            padding: 2px 2px;
            font-size: 16px;
            cursor: pointer;
        }
        /* Orange */
        .ShopingBtn {
            border-color: #ff9800;
            color: orange;
        }

            .ShopingBtn:hover {
                background: #ff9800;
                color: white;
            }
    </style>
</head>

@if (Request.IsAuthenticated)
{
    <div class="dropdown">
        <button class="btn1 ShopingBtn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="~/SourceIMG/Shopping_cart_1.jpg" alt="Shopping_Cart" width="43" height="43">
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayName("Ticket Name")
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayName("Amount")
                    </th>

                    <th></th>
                </tr>
                @*@{
                        UserTicketsController controller = new UserTicketsController();
                        controller.SetViewBagShoppingCart();
                    }*@
                @if (Session["TicketsBought"] != null)
                {
                    foreach (var item in Session["TicketsBought"] as List<WebApp.Models.DisplayShopingCartTicket>)
                    {
                        <tr>
                            <td>
                                @item.TicketName
                            </td>
                            <td>
                                @item.Price
                            </td>
                            <td>
                                @item.AmountBought
                            </td>
                            <td>
                                    @Html.ActionLink("X", "RemoveFromShopingList", "UserTickets", new { id = item.Id }, null)
                                </td>
                            @*<td>
                                <div id="Button">
                                    <button onclick="RemoveTicket(new { id = item.Id })"> X </button>
                                </div>
                            </td>*@
                        </tr>
                    }
                }
                else
                {
                }
            </table>
            @if (Session["TicketsBought"] != null)
            {
                <button>@Html.ActionLink("Buy", "ShoppingCartOverview", "Shared")</button>
            }
            @*@Html.ActionLink("Buy", "CompleteTransaction", "UserTickets", new { userId = User.Identity.GetUserId() }, null)*@
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        function RemoveTicket(id) {
            $.ajax({
                type: "GET",
                data: { id },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                url: "/UserTickets/RemoveFromShopingList",
                success: function () {
                    alert("Alex was here!")
                }
            });
        };
    </script>
    }

3rd Semester Project/WebApp/Views/Shared/ShoppingCartOverview.cshtml
@using Microsoft.AspNet.Identity
@using WebApp.Controllers;
@using WebApp.Models;
@model IEnumerable<WebApp.Models.DisplayShopingCartTicket>

<h1>Shopping Cart Overview</h1>

<head>
    @section css {
        <link href="@Url.Content("~/Content/ShoppingCartOverview.css")" rel="stylesheet" />
    }
</head>

<body>
    <main>
        <div class="basket">
            <div class="basket-labels">
                <ul>
                    <li class="item item-heading">Item</li>
                    <li class="names">Names</li>
                    <li class="price">Price</li>
                    <li class="quantity">Quantity</li>
                    <li class="subtotal">Subtotal</li>
                </ul>
            </div>

            @if (Session["TicketsBought"] != null)
            {
                foreach (var item in Session["TicketsBought"] as List<WebApp.Models.DisplayShopingCartTicket>)
                {
        <div class="basket-product">
            <div class="item">
                <div class="product-details">
                    <h1><strong><span class="item-quantity">@item.AmountBought</span>x @item.TicketName </strong> </h1>
                </div>
            </div>
            <div class="names">
                @foreach (BuyerName buyer in item.GetListOfBuyerNames())
                {
                    <p>@buyer.FirstName @buyer.LastName</p>
                }
            </div>
            <div class="price"> @item.Price </div>
            <div class="quantity">
                <input class="quantity-field" readonly value="@item.AmountBought">
            </div>
            <div class="subtotal"></div>
            <div class="remove">
                @*@Html.ActionLink("Remove", "RemoveFromShopingList", new { id = item.Id }, new { @class = "deleteButton" })*@
                <button class="remove" onclick="removeItem(@item.Id)">Remove</button>
            </div>
        </div>
                }
            }

            
        </div>
        <aside>
            <div class="summary">
                <div class="summary-total-items"><span class="total-items"></span> Items in your Bag</div>
                <div class="summary-total">
                    <div class="total-title">Total</div>
                    <div class="total-value final-value" id="basket-total"></div>
                </div>
                <div class="summary-checkout">
                    <button class="checkout-cta">Checkout</button>
                </div>
            </div>
        </aside>
    </main>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        var fadeTime = 300;

        //$('.remove button').click(function () {
        //    removeItem(this);
        //});

        $('.checkout-cta').click(function () {
            recalculateCart(true);
            checkout();
        });

        $(document).ready(function () {
            updateSumItems();
            calculateSubtotals();
            recalculateCart(true);
        });


        /* Recalculate cart */
        function recalculateCart(onlyTotal) {
            var subtotal = 0;

            /* Sum up row totals */
            $('.basket-product').each(function () {
                subtotal += parseFloat($(this).children('.subtotal').text());
            });

            /* Calculate totals */
            var total = subtotal;
            if (total == 0) { $('.checkout-cta').fadeOut(fadeTime); }

            /*If switch for update only total, update only total display*/
            if (onlyTotal) {
                /* Update total display */
                $('.total-value').fadeOut(fadeTime, function () {
                    $('#basket-total').html(total.toFixed(2));
                    $('.total-value').fadeIn(fadeTime);
                });
            } else {
                /* Update summary display. */
                $('.final-value').fadeOut(fadeTime, function () {
                    $('#basket-subtotal').html(subtotal.toFixed(2));
                    $('#basket-total').html(total.toFixed(2));
                    if (total == 0) {
                        $('.checkout-cta').fadeOut(fadeTime);
                    } else {
                        $('.checkout-cta').fadeIn(fadeTime);
                    }
                    $('.final-value').fadeIn(fadeTime);
                });
            }
        }

        function calculateSubtotals() {
            var subtotal = 0;
            $('.basket-product').each(function () {
                subtotal = (parseFloat($(this).children('.price').text()) * parseFloat($(this).children('.quantity').children('.quantity-field').val()));
                $(this).children('.subtotal').text(subtotal);
                subtotal = 0;
            });
        }

        function updateSumItems() {
            var sumItems = 0;
            $('.quantity-field').each(function () {
                sumItems += parseInt($(this).val());
            });
            $('.total-items').text(sumItems);
        }

        /* Remove item from cart */
        function removeItem(id) {
            /* Remove row from DOM and recalc cart total */
            var productRow = $('.remove button').parent().parent();
            productRow.slideUp(fadeTime, function () {
                    removeFromShoppingList(id);
                    productRow.remove();
                    recalculateCart();
                    updateSumItems();
            });
        }

        function removeFromShoppingList(id) {
            $.ajax({
                type: "GET",
                url: "/UserTickets/RemoveFromShopingList/" + id,
                success: function () {
                    location.href = "/Shared/ShoppingCartOverview";
                }
            });
        };

        function checkout() {
            localStorage.setItem('price', $('#basket-total').text());
                $.ajax({
                    type: "GET",
                    url: "/Shared/PaymentGateway",
                    success: function () {
                        location.href = "/Shared/PaymentGateway" ;
                    }
                });
        };
        
    </script>

}

3rd Semester Project/WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using WebApp.Models
<!DOCTYPE html>
<style>
    /*body {
        background-image: url('https://i.pinimg.com/originals/b7/ff/e5/b7ffe556b5c07784ab6ee8e58ee08881.jpg');
    }*/
body { background-image: url('https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700320488.jpg'); }
</style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="~/SourceIMG/images.png" alt="Image" width="43" height="43">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FerryRides", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Trip", "ListOfTrips", "Trip")</li>
                    @if (User.IsInRole("Business") || User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("My Trips", "ListOfTrips", "Trip", new { userId = User.Identity.GetUserId() }, null)</li>
                    }
                    <li>@Html.ActionLink("Purchase history", "ListOfUserTickets/" + User.Identity.GetUserId(), "UserTickets")</li>
                    <li>@Html.Partial("ShoppingCart", new List<DisplayShopingCartTicket>())</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>